Vagrant.configure("2") do |config|
  config.vm.define "sonarqube" do | node |
    node.vm.box_download_insecure = true    
    node.vm.box = "hashicorp/bionic64"
	node.vm.provision :shell, path: "Bootstrap.sh"
    node.vm.network "private_network", ip: "192.168.0.101"
    node.vm.hostname = "sonarqube"
    node.vm.provider "virtualbox" do | v |
      v.name = "sonarqube"
      v.memory = 2048
      v.cpus = 1
    end
  end
end
