Vagrant.configure("2") do |config|
  config.vm.define "nexus" do | node |
    node.vm.box_download_insecure = true    
    node.vm.box = "hashicorp/bionic64"
	node.vm.provision :shell, path: "Bootstrap.sh"
    node.vm.network "private_network", ip: "192.168.0.102"
    node.vm.hostname = "nexus"
    node.vm.provider "virtualbox" do | v |
      v.name = "nexus"
      v.memory = 2048
      v.cpus = 1
    end
  end
end
