Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do | node |
    node.vm.box_download_insecure = true    
    node.vm.box = "hashicorp/bionic64"
	node.vm.provision :shell, path: "Bootstrap.sh"
    node.vm.network "private_network", ip: "192.168.0.100"
    node.vm.hostname = "jenkins"
    node.vm.provider "virtualbox" do | v |
      v.name = "jenkins"
      v.memory = 4096
      v.cpus = 1
    end
  end
end
